In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
sns.set()

In [3]:
data=pd.read_csv("1.02.+Multiple+linear+regression.csv")
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [4]:
y=data["GPA"]
x=data[["SAT","Rand 1,2,3"]]

In [5]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression()

In [6]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

0.29603261264909486

In [8]:
reg.score(x,y)

0.40668119528142843

In [11]:
x.shape
# here 84 is value of n and p is 2

(84, 2)

In [16]:
def adjusted_r2(reg,x):
    n=x.shape[0]
    p=x.shape[1]
    return 1-(1-reg.score(x,y))*((x.shape[0]-1)/(x.shape[0]-x.shape[1]-1))

In [17]:
adjusted_r2(reg,x)

0.39203134825134023

F regression 


In [18]:
from sklearn.feature_selection import f_regression


In [19]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [23]:
p_values=f_regression(x,y)[1]
p_values.round(3)

array([0.   , 0.676])

Summary table


In [25]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=["Features"])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [26]:
reg_summary["Coefficients"]=reg.coef_
reg_summary["p_values"]=p_values.round(3)


In [29]:
reg_summary

Features  Coefficients  p_values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

Standardization

In [30]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [31]:
scaler.fit(x)

StandardScaler()

In [32]:
x_scaled=scaler.transform(x)

In [34]:
reg.fit(x_scaled,y)

LinearRegression()

In [36]:
reg.intercept_

3.330238095238095

In [37]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [42]:
reg_summary=pd.DataFrame([["Intercept/Bias"],["SAT"],["Rand 1,2,3"]],columns=["Features"])
reg_summary["Weights"]=reg.intercept_,reg.coef_[0],reg.coef_[1]

In [43]:
reg_summary

Features   Weights
0  Intercept/Bias  3.330238
1             SAT  0.171814
2      Rand 1,2,3 -0.007030

Predictions with standardized data

In [44]:
new_data=pd.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [45]:
new_data_scaled=scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [47]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])