In [1]:
import numpy as np
from sklearn.model_selection import train_test_split


In [2]:
a=np.arange(1,101)
b=np.arange(501,601)

In [5]:
a_train,a_test=train_test_split(a,test_size=0.2)

In [6]:
a_test

array([ 35,   9,  38,  98,  20,  75,  86,  49,  15,  55,  72,  95,  45,
        13,  36,  83,  41,  93, 100,  33])

In [7]:
a_train

array([68, 60, 85,  1, 14, 62,  4, 26, 74,  7, 31, 63, 65, 46, 17, 77, 96,
       48, 42, 58, 29, 91, 70, 69, 10, 97, 18, 28, 52, 12,  6, 66, 80, 23,
       24, 19,  2, 11, 43, 92, 40, 89,  5, 79, 99, 37, 64, 22, 82, 90, 61,
       53, 67, 94, 84, 51, 87, 47, 56, 50, 76, 54, 30,  3, 57, 34, 71, 44,
       78, 59, 88, 32, 39, 16, 27, 25, 21, 81, 73,  8])

In [11]:
a_lock_train,a_lock_test=train_test_split(a,test_size=0.2,random_state=42)

In [12]:
a_lock_train



array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])